added helm client install routine

diff --git a/01-import-SSH-public-key/kickstart.yaml b/01-import-SSH-public-key/kickstart.yaml
--- a/01-import-SSH-public-key/kickstart.yaml
+++ b/01-import-SSH-public-key/kickstart.yaml
@@ -182,14 +182,34 @@ resources:
               echo "# Installing kubectl client"
               sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
               if which kubectl >/dev/null; then (echo "# Finished kubectl client setup"; exit 0) else (echo "# Error while installing kubectl client"; exit 99); fi
-           path: /root/kubectl-install.sh
+              echo "# Configuring kubectl and installing plugins"
+              mkdir /home/syseleven/.kube
+              echo "source <(kubectl completion bash)" >> /home/syseleven/.bashrc
+              echo "alias k=kubectl" >>  /home/syseleven/.bashrc
+              echo "complete -o default -F __start_kubectl k" >> /home/syseleven/.bashrc
+           path: /root/kubectlclient-install.sh
+           owner: root
+           permissions: 0700
+         - content: |
+              #!/usr/bin/env bash
+              cd /tmp
+              echo "# Downloading helm client"
+              curl -LO https://get.helm.sh/helm-v3.10.2-linux-amd64.tar.gz
+              echo "# Installing helm client"
+              tar -zxvf helm-v3.10.2-linux-amd64.tar.gz
+              mv linux-amd64/helm /usr/local/bin/helm
+              echo "# Installing helm diff plugin"
+              if which helm >/dev/null; then (echo "# Finished helm client setup"; exit 0) else (echo "# Error while installing helm client"; exit 99); fi
+              helm plugin install https://github.com/databus23/helm-diff
+           path: /root/helmclient-install.sh
            owner: root
            permissions: 0700
        runcmd:
          - /root/inject_userkey
          - /root/terra-install.sh
          - /root/openstackclient-install.sh
-         - /root/kubectl-install.sh
+         - /root/kubectlclient-install.sh
+         - /root/helmclient-install.sh
        packages:
          - git
          - wget
